# Generated by Django 4.2.3 on 2024-07-03 10:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "path",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("vehicle_id", models.CharField(max_length=100, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("bus", "Bus"), ("train", "Train"), ("tram", "Tram")],
                        max_length=50,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("speed", models.FloatField(default=0)),
                ("heading", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
