name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:13-3.1
        env:
          POSTGRES_DB: urbanpulse_test
          POSTGRES_USER: urbanpulse
          POSTGRES_PASSWORD: urbanpulse_password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils libproj-dev gdal-bin
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      env:
        DATABASE_URL: postgis://urbanpulse:urbanpulse_password@localhost:5432/urbanpulse_test
      run: python manage.py migrate
    - name: Run tests
      env:
        DATABASE_URL: postgis://urbanpulse:urbanpulse_password@localhost:5432/urbanpulse_test
      run: python manage.py test